### ISSUE TITLE
Is it possible to mute only minimized apps?

### ISSUE THREAD

**Issue by Rik-Kirtaniya** [nefares/Background-Muter#13] opened 2022-07-28 17:58 UTC
Use case scenario: I am running two windows A and B side by side, A is playing audio but I need to click on B occasionally, which causes A to turn into a non-active window and thus get muted.

Is it possible to make it so that the window gets muted _**only**_ when minimized to taskbar but not when it is merely clicked outside of and made non-active?

**Comment by nefares** [comment] 2022-08-08 03:34
Added as a feature request. This can be implemented as a global setting, so it will affect the muting behavior overall and not for specific windows.

**Comment by lamrongol** [comment] 2022-11-16 05:04
I also want this feature and sent pull request.
https://github.com/nefares/Background-Muter/pull/17

**Comment by nefares** [comment] 2022-11-26 02:21
Please confirm the closure of this issue

**Comment by Rik-Kirtaniya** [comment] 2022-11-26 02:51
@nefares Works perfectly according to my testing. Thanks a lot to both you and @lamrongol for making this feature.

(Now I can have my visual novels running in the background without having to close them every time I want to do something else. :D)

**Comment by lamrongol** [comment] 2022-11-26 06:34
I confirmed this works correctly at the moment.

**Comment by lamrongol** [comment] 2022-11-27 11:08
Hmm... I restarted Windows and this doesn't work before once changing config.

**Comment by nefares** [comment] 2022-11-27 22:44
Thanks for the positive feedback!

@lamrongol  will close this for now since the feature is implemented. Can you create a separate issue for the bug you encountered.

**Closed by nefares** 2022-11-27 22:44 UTC
Labels: enhancement
