### ISSUE TITLE
There are two problems that are inconvenient to use.

### ISSUE THREAD

**Issue by Lioreas** [nefares/Background-Muter#8] opened 2022-06-10 01:24 UTC
The first is that when i turn on Enable autostart, the volume is turned off for programs that i didn't leave as mute exception before double-clicking on the tray.(Working after double-clicking on the tray)

Second, after changing the program, the "Setting changed" window appears every time i turn off the program even though i press Save changes. (If there is no change, it does not appear.)
This causes problems that i have to press the shutdown button each time you turn off the computer, ignore the program's warning, or press the Cancel button, press yes for this program, and then turn it off again.

**Comment by nefares** [comment] 2022-06-20 19:30
Thanks for  the report. 

Regarding the second point I have provided a fix in the latest release 1.0.5: https://github.com/nefares/Background-Muter/releases/tag/v1.0.5

Regarding the first point: I'm not able to replicate this. Could you give me the steps to re-create the issue? Enabling autostart should have no effect on the Mute/Unmute functionality.

**Comment by Lioreas** [comment] 2022-06-22 13:24
> Thanks for the report.
> 
> Regarding the second point I have provided a fix in the latest release 1.0.5: https://github.com/nefares/Background-Muter/releases/tag/v1.0.5
> 
> Regarding the first point: I'm not able to replicate this. Could you give me the steps to re-create the issue? Enabling autostart should have no effect on the Mute/Unmute functionality.

**Comment by Lioreas** [comment] 2022-06-22 14:09
I think the syntax of Background Muter.lnk in the startup program -- startMinimized works differently for each computer. In my case, programs that are not handled as exceptions in the GUI will remain muted until I run the GUI in the tray.

This seems to be because --startMinimized does not complete the execution.

**Comment by lamrongol** [comment] 2024-08-17 12:53
> I guess --startMinimized is making the execution weird.

I think so, too. I found BG Muter doesn't work when booted by "Autostart", which has `--startMinimized` option. It starts to work when clicking the tray icon and the form is displayed.

I confirmed `RunMuter()` is not fired when booted with `--startMinimized` option and `RunMuter()` is executed by `MuterCallback()` which is excecuted by `MuterTimer_Tick`, and the following post says `tick` is affected when the form is minimized:
https://stackoverflow.com/q/2166773/3809427

However, once the form is displayed, even if it retuns to tray icon, it works continually.
I can't understand this phenomenon any more.

**Comment by lamrongol** [comment] 2024-08-18 13:18
I found a released binary file's form title is 
![image](https://github.com/user-attachments/assets/370e12e8-310e-42f1-961c-c4f8817ca758)

However, I pulled the newest source code(I confirmed that it is not different from released source code) and compiled and run, Title of the form is:
![image](https://github.com/user-attachments/assets/64190e8b-c59b-4ce7-b45c-2816a4ac2a16)

This difference originate from `WinBGMuter.dll` which is l.509~516 of `MainForm.cs`.
I don't know what it mean but this may cause the problem in different environments.

**Comment by nefares** [comment] 2024-08-22 22:51
@Lioreas This is definitly a bugThe original code prevents the `MainForm_Load` from executing, causing the muter to never actually initialize.  @lamrongol I have merged your code into the master branch with some small changes (the minimizing code is now under the `Shown` event of the `MainForm`

Lastest release is under: [https://github.com/nefares/Background-Muter/releases/tag/v1.0.10](https://github.com/nefares/Background-Muter/releases/tag/v1.0.10)

**Closed by nefares** 2024-08-22 22:51 UTC
Labels: bug

**Comment by nefares** [comment] 2024-08-22 22:55
> I found a released binary file's form title is ![image](https://private-user-images.githubusercontent.com/4645074/358908182-370e12e8-310e-42f1-961c-c4f8817ca758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjY3NjYsIm5iZiI6MTcyNDM2NjQ2NiwicGF0aCI6Ii80NjQ1MDc0LzM1ODkwODE4Mi0zNzBlMTJlOC0zMTBlLTQyZjEtOTYxYy1jNGY4ODE3Y2E3NTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMjI0MTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjlhOWFjZDQ1MzVkYWY4MDdhZDc4ZGZkMzliYThhMTdiNzlkOGNjZGY1NmY2YTE5OTAxZmI1OTZlYzg1NDY2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ddKNIkqmz5faw1Y25k63rKM1nVANdfyQraPJBl8jThY)
> 
> However, I pulled the newest source code(I confirmed that it is not different from released source code) and compiled and run, Title of the form is: ![image](https://private-user-images.githubusercontent.com/4645074/358908074-64190e8b-c59b-4ce7-b45c-2816a4ac2a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjY3NjYsIm5iZiI6MTcyNDM2NjQ2NiwicGF0aCI6Ii80NjQ1MDc0LzM1ODkwODA3NC02NDE5MGU4Yi1jNTliLTRjZTctYjQ1Yy0yODE2YTRhYzJhMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMjI0MTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2QzNzNlYzZjMjBkZGJlZGMzYTMxNTNlZTdlZDU2OGY2YjZhMmUwNGQ5Y2M2NDYyZDNiMTlmYTVhYjMyZDZlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pxf_5ATWAgjRrjgrz3mea4UMOXpx-db_gVKWWi8r600)
> 
> This difference originate from `WinBGMuter.dll` which is l.509~516 of `MainForm.cs`. I don't know what it mean but this may cause the problem in different environments.

This behavior is caused by the build process. When building locally, the app will include a genetic version with the latest commit. When building using Github Actions CI/CD, it will automatically take the latest release number and show it in Background muter.  Feel free to read the github actions file here: https://github.com/nefares/Background-Muter/blob/master/.github/workflows/tagged-release.yml
